export const BACKGROUND = {
  LOWER_HEIGHT: 85,
  SPEED: 3,
  UPPER_HEIGHT: 515,
};

export const BIRD = {
  ANIMATION_SPEED: 10,
  GRAVITY: 0.5,
  HEIGHT: 44,
  INITIAL_VELOCITY: -2,
  INITIAL_X_POSITION: 100,
  INITIAL_Y_POSITION: 250,
  JUMP_INITIAL_SPEED: 10,
  WIDTH: 62,
};

export const CANVAS = {
  HEIGHT: 600,
  WIDTH: 500,
};

export const DIFFICULTY = {
  EASY: 'Easy',
  HARD: 'Hard',
  NORMAL: 'Normal',
};

export const PIPE = {
  DIFFICULTY_ADJUSTMENT: 50,
  SPACE_BETWEEN_PIPES: 200,
  SPEED: 3,
  WIDTH: 100,
};

export const STATE = {
  BIRDCRASHED: 'BIRDCRASHED',
  ENDGAME: 'ENDGAME',
  PLAYING: 'PLAYING',
  PREGAME: 'PREGAME',
};
